-- The dev user's Leitner file (docs/lesetext-plan.md §1).
--
-- Generated by `scripts/gen-reading-seed.py`. Each card is about a lexeme from `vocabulary.sql`,
-- which is what lets the reading text tint a word the learner has a card for: the text's span and
-- the card point at the same row. `front`/`back` are the learner's own copy of it.
--
-- Twelve cards are due today across the six boxes and three rest higher up, so "12 Karten fällig"
-- on the home screen is real. `last_reviewed_at` is the day each card's own schedule implies (due
-- minus that box's interval), so "gelernt" and "in 30 Tagen" cannot disagree over seeded history.

with v (front, lexeme_id, back, example, box, due, reviews, lapses) as (values
  ('à emporter', '34c0ada4-914d-5932-a3b9-1a93ccaa87f0', 'zum Mitnehmen', 'un café à emporter', 1, current_date, 5, 2),
  ('l’addition', 'ba265cca-bd3f-5d8b-b57a-6a2bcaa628f5', 'die Rechnung', 'L’addition, s’il vous plaît.', 1, current_date, 3, 1),
  ('se débrouiller', 'fa345a8f-ff01-522d-90bb-8395b7e06986', 'sich zurechtfinden', 'Je me débrouille en français.', 1, current_date, 4, 2),
  ('pourtant', '8dc29326-0809-547f-b629-a55cf7f74331', 'dennoch', 'Il pleut, pourtant je sors.', 1, current_date, 2, 1),
  ('le quartier', '83741302-3b2f-5345-bf38-73b16efe387d', 'das Viertel', 'J’habite dans ce quartier.', 2, current_date, 6, 1),
  ('le rendez-vous', 'd8453cd5-2b76-5914-a093-d658059859b8', 'der Termin', 'J’ai un rendez-vous à midi.', 2, current_date, 3, 0),
  ('le trajet', 'e7deac52-30b0-55fc-a2a3-10603642d6f8', 'der Weg', 'Le trajet dure vingt minutes.', 2, current_date, 3, 0),
  ('déjà', 'e38aa4a8-e239-52b1-af82-919f215e1825', 'schon', 'Tu es déjà là ?', 3, current_date, 5, 0),
  ('le lait', '744e5fb8-1a87-523a-8a06-39b24f759b90', 'die Milch', 'un café avec du lait', 3, current_date, 4, 0),
  ('chaud', '33a9c48d-03b8-5970-8bd4-2c64cebdb155', 'heiß', 'un café chaud', 4, current_date, 7, 0),
  ('le café', '36b07e01-ac6f-50fe-a445-e23283196901', 'der Kaffee', 'un café, s’il vous plaît', 4, current_date, 8, 0),
  ('s’il vous plaît', 'a577e9a9-0bdc-5be0-8339-a9146f8747e7', 'bitte', 'Un latte, s’il vous plaît.', 5, current_date, 9, 0),
  ('emménager', '3fd4679f-9357-5dcc-87ae-bf0d42781549', 'einziehen', 'On emménage samedi.', 4, current_date + 5, 4, 1),
  ('le carrefour', '9c5adf13-8a9c-5b69-b48d-b1a8a1162b49', 'die Kreuzung', 'Tournez au carrefour.', 5, current_date + 12, 6, 0),
  ('soudain', '2f69f303-b5fa-5d26-83ea-88e9c036fbce', 'plötzlich', 'Soudain, il s’est arrêté.', 6, current_date + 25, 9, 0)
)
insert into public.flashcards
  (user_id, language, front, back, back_language, example, lexeme_id, box, due, reviews, lapses,
   last_reviewed_at)
select '00000000-0000-0000-0000-000000000001', 'fr', v.front, v.back, 'de', v.example, v.lexeme_id::uuid, v.box, v.due,
       v.reviews, v.lapses,
       (v.due - (array[0, 2, 4, 8, 16, 32])[v.box])::timestamptz
from v
on conflict (user_id, lexeme_id) do nothing;
